### ISSUE TITLE
fails to compile from source

### ISSUE THREAD

**Issue by jimmon89** [Synthlight/Volcanoids-GMod#1]
I'm sure it works on your end, and I'm even more sure my issue is that I'm just missing a lib or dependency somewhere along the chain.

with the current master the error is as follows
`
Build started...
1>------ Build started: Project: Base-Mod, Configuration: Debug x64 ------
1>Base-Mod -> B:\Jimmy\source\repos\Base-Mod\bin\x64\Debug\Base-Mod.dll
2>------ Build started: Project: GMod, Configuration: Debug x64 ------
2>B:\Jimmy\source\repos\Volcanoids-GMod\Plugin.cs(19,33,19,43): error CS0103: The name 'ConfigFile' does not exist in the current context
2>B:\Jimmy\source\repos\Volcanoids-GMod\Plugin.cs(20,49,20,59): error CS0103: The name 'ConfigFile' does not exist in the current context
2>B:\Jimmy\source\repos\Volcanoids-GMod\Plugin.cs(29,35,29,45): error CS0103: The name 'ConfigFile' does not exist in the current context
2>Done building project "GMod.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

and rolling back to the v1.11 tag has no effect resulting in the same errors
`
Build started...
1>------ Build started: Project: Base-Mod, Configuration: Release x64 ------
1>Base-Mod -> B:\Jimmy\source\repos\Base-Mod\bin\x64\Release\Base-Mod.dll
2>------ Build started: Project: GMod, Configuration: Release x64 ------
2>B:\Jimmy\source\repos\Volcanoids-GMod-1.11\Plugin.cs(19,33,19,43): error CS0103: The name 'ConfigFile' does not exist in the current context
2>B:\Jimmy\source\repos\Volcanoids-GMod-1.11\Plugin.cs(20,49,20,59): error CS0103: The name 'ConfigFile' does not exist in the current context
2>B:\Jimmy\source\repos\Volcanoids-GMod-1.11\Plugin.cs(29,35,29,45): error CS0103: The name 'ConfigFile' does not exist in the current context
2>Done building project "GMod.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by Synthlight** [comment]
The problem isn't here, but rather you using a commit from base mod that's too new. Roll base mod back to `e6d4c4d` and it'll work just fine.
I will not be updating this to match till the next updated releases.

**Comment by jimmon89** [comment]
thank you for the tip, I'll give that a shit and report back
--edit--
that did the trick, thank you very much.
I really appreciate the help.
