### ISSUE TITLE
Log(s) file u asked for.

### ISSUE THREAD

**Issue by SGZ-Creations** [Synthlight/Volcanoids-GMod#2]
[Player.log](https://github.com/Synthlight/Volcanoids-GMod/files/11858038/Player.log)
[Player-prev.log](https://github.com/Synthlight/Volcanoids-GMod/files/11858039/Player-prev.log)

**Comment by Synthlight** [comment]
```
GMod loading.
Patched: ToolCameraTravel:Void Update()
Patched: TrainRuntime:Boolean get_IsClaimable()
Patched: TrainCoreAccess:Boolean CanInstall(TrainCoreItemDefinition, Int32, Boolean)
Patched: TrainCoreAccess:Boolean IsBetterCore(TrainCoreItemDefinition, TrainCoreItemDefinition)
Patched: HelpCrosshairUi:Void Update()
Patched: WeaponReloaderDefault:Boolean LoadAmmo(InventoryBase, ItemDefinition, Int32)
Patched: WeaponReloaderDefault:Boolean UnloadAmmo()
Patched: Inventory:Int32 get_Capacity()
Patched: UnityEngine.AudioSource:Void PlayOneShot(UnityEngine.AudioClip, Single)
Patched: TrainUpgrades:Single get_Radar()
Patched: WeaponAnimationDuration:Single get_SpeedMultiplier()
Patched: PlayerMovement:Single get_RunSpeed()
Patched: Stamina:Single get_CurrentStamina()
Patched 13 methods.
GMod loaded.
```
There's nothing wrong in that log. All mods are initializing without issue.
I did have to fix other issues like the base framework changing from `netstandard20` to `netstandard21`, and the turret ammo stuff changing, and big updates always break thigs so... for future reference... if shit isn't working an hour after the update... just have a bit of patience.

It should all be working now. At least it is on my machine.

**Comment by SGZ-Creations** [comment]
i updated things still broken but maybe not your end.
